"""Field-of-view layout and grid-clustering math shared across every
OME-NGFF writer (nd2-sourced, TIFF-sourced, and future Operetta-sourced).

Nothing in this module reads any particular source format directly -- it
only operates on already-extracted stage positions, tile shapes, and channel
metadata, so it has no dependency on ``nd2``/``bioio`` at all.
"""
from typing import List, Tuple, Union, Optional
from pathlib import Path
import re
import logging

from ngio import Roi, RoiTable
import numpy as np

logger = logging.getLogger(__name__)

# Matches "C09", "AA12", etc. -- one or more letters (row) followed by digits
# (column).
_WELL_NAME_RE = re.compile(r"^([A-Za-z]+)(\d+)")
# Matches a well name embedded in a filename, e.g. "WellC09_Channel...".
_FILENAME_WELL_RE = re.compile(r"Well([A-Za-z]+\d+)")


class FieldLayout:
    """Stage-position-derived layout for stitching a source file's fields of
    view into one mosaic canvas.

    Attributes
    ----------
    row, column
        Well identifier, parsed from the source file's own position-name
        metadata (preferred) or its filename (fallback).
    offsets
        One ``(y0, x0)`` pixel offset per field, in field/position order.
    tile_shape
        ``(T, C, Z, Y, X)`` shape of a single field.
    canvas_shape
        ``(T, C, Z, Y, X)`` shape of the full stitched mosaic.
    pixel_size_x, pixel_size_y, pixel_size_z
        Physical pixel size in micrometers.
    channel_names, channel_colors
        One entry per channel, from the source file's own channel metadata.
    position_names
        One position ``name`` per field, in the same order as ``offsets``.
        ``None`` for a field with no recorded position name (e.g. a
        single-position file).
    field_ids
        One stable, source-assigned integer field identifier per field, in
        the same order as ``offsets`` -- 1-indexed position order for an
        nd2-sourced layout, the metadata sidecar's own ``field_id`` column
        for a TIFF-sourced one. Keys the global object-id formula in
        :mod:`blimp.ome_ngff.labels`/:mod:`blimp.ome_ngff.features`.
    """

    def __init__(
        self,
        row: str,
        column: int,
        offsets: List[Tuple[int, int]],
        tile_shape: Tuple[int, int, int, int, int],
        canvas_shape: Tuple[int, int, int, int, int],
        pixel_size_x: float,
        pixel_size_y: float,
        pixel_size_z: float,
        channel_names: List[str],
        channel_colors: List[str],
        position_names: List[Optional[str]],
        field_ids: Optional[List[int]] = None,
    ):
        self.row = row
        self.column = column
        self.offsets = offsets
        self.tile_shape = tile_shape
        self.canvas_shape = canvas_shape
        self.pixel_size_x = pixel_size_x
        self.pixel_size_y = pixel_size_y
        self.pixel_size_z = pixel_size_z
        self.channel_names = channel_names
        self.channel_colors = channel_colors
        self.position_names = position_names
        self.field_ids = field_ids if field_ids is not None else list(range(1, len(offsets) + 1))


def _parse_well_name(source_path: Union[str, Path], position_names: List[Optional[str]]) -> Tuple[str, int]:
    """Determine a well's row/column identifier.

    Prefers position-name metadata (e.g. a position named ``"C09_0000"``)
    over the filename, since it is generated by the acquisition software
    itself rather than a naming convention that could be lost on copy/rename.

    Parameters
    ----------
    source_path
        Full path to the source file (used for the filename fallback).
    position_names
        Position ``name`` values, one per field of view. May contain
        ``None`` entries, or be a single ``[None]`` when no position-name
        metadata is available at all (e.g. a TIFF-sourced layout).

    Returns
    -------
    (row, column)
        e.g. ``("C", 9)``.

    Raises
    ------
    ValueError
        If no well identifier can be determined from either source.
    """
    for name in position_names:
        if name is None:
            continue
        match = _WELL_NAME_RE.match(name)
        if match is not None:
            return match.group(1).upper(), int(match.group(2))

    filename_match = _FILENAME_WELL_RE.search(Path(source_path).stem)
    if filename_match is not None:
        well_match = _WELL_NAME_RE.match(filename_match.group(1))
        if well_match is not None:
            return well_match.group(1).upper(), int(well_match.group(2))

    raise ValueError(
        f"Could not determine a well identifier for {source_path} from its position names or filename. "
        "Expected a position name or filename containing e.g. 'C09'."
    )


def _cluster_grid_index(values: np.ndarray, tile_extent: float) -> np.ndarray:
    """Assign each stage-coordinate value a 0-indexed row/column cluster.

    Fields meant to sit on the same nominal row/column can still differ by a
    small amount (a few percent of the tile extent) -- stage positioning
    jitter, or a slight rotation between
    the stage and camera axes. Using that raw value directly as a pixel
    offset (see :func:`_exact_pixel_offset`) bakes the jitter into the
    canvas as a small but visible misalignment between tiles that are meant
    to sit flush (fields are acquired with no deliberate overlap).
    Clustering first, then placing each cluster at an exact multiple of the
    tile size, snaps to the intended grid instead.

    Parameters
    ----------
    values
        Raw stage coordinates along one axis, one per field.
    tile_extent
        Tile size along that axis, in the same physical units as ``values``.

    Returns
    -------
    numpy.ndarray
        0-indexed cluster id per field, in ``values``' original order.
    """
    order = np.argsort(values)
    cluster = np.zeros(len(values), dtype=int)
    next_id = 0
    for i in range(1, len(order)):
        if values[order[i]] - values[order[i - 1]] > tile_extent / 2:
            next_id += 1
        cluster[order[i]] = next_id
    return cluster


def _exact_pixel_offset(stage: np.ndarray, pixel_size: float, reverse: bool) -> np.ndarray:
    """Convert raw stage coordinates directly to pixel offsets, without the
    grid-snapping :func:`_cluster_grid_index` does.

    More faithful to the actual recorded positions than grid placement --
    prefer it when fields have genuine deliberate overlap, or nominal
    positions are not expected to fall on a regular grid. ``reverse`` flips
    the axis (e.g. stage-x increasing while pixel-x decreases), matching
    ``x_direction="left"``/``y_direction="up"`` in
    :func:`nd2_to_ome_ngff.get_field_layout`/
    :func:`tiff_to_ome_ngff.get_field_layout_from_tiff_metadata`.

    Parameters
    ----------
    stage
        Raw stage coordinates along one axis, one per field.
    pixel_size
        Physical pixel size along that axis, in the same units as ``stage``.
    reverse
        Whether increasing ``stage`` should map to decreasing pixel offset.

    Returns
    -------
    numpy.ndarray
        Pixel offset per field, in ``stage``'s original order.
    """
    if reverse:
        return np.round((stage.max() - stage) / pixel_size).astype(int)
    return np.round((stage - stage.min()) / pixel_size).astype(int)


def _build_fov_roi_table(layout: FieldLayout) -> RoiTable:
    """Build a Fractal/``ngio``-style ``"FOV_ROI_table"`` recording each
    original field of view's pixel region within the stitched mosaic.

    Downstream per-FOV processing (e.g. illumination correction, which must
    be computed against the original camera frame, not an arbitrary crop of
    the stitched canvas) reads this table to recover field boundaries that
    are otherwise lost once fields are merged into one contiguous array.
    Not part of the core NGFF spec -- a Fractal/``ngio`` convention, see
    ``fractal_tasks_core/illumination_correction.py``.

    ROIs are recorded in world (physical) coordinates -- ``ngio``'s
    ``RoiTable`` only supports serializing world-coordinate ROIs -- with
    ``z`` left unconstrained, so the same table resolves correctly against
    both the full z-stack and the MIP image of the same well.

    Parameters
    ----------
    layout
        As returned by :func:`get_field_layout`/
        :func:`get_field_layout_from_tiff_metadata`.

    Returns
    -------
    RoiTable
    """
    pixel_size_x = layout.pixel_size_x if layout.pixel_size_x and layout.pixel_size_x > 0 else 1.0
    pixel_size_y = layout.pixel_size_y if layout.pixel_size_y and layout.pixel_size_y > 0 else 1.0
    if not (layout.pixel_size_x and layout.pixel_size_x > 0) or not (layout.pixel_size_y and layout.pixel_size_y > 0):
        logger.warning(
            "Missing or non-positive pixel size in source metadata; falling back to "
            "1.0 micrometer/pixel for the FOV ROI table. ROI extents will be wrong "
            "in physical units (still correct in pixel count) until this is fixed "
            "at the source."
        )

    h, w = layout.tile_shape[3], layout.tile_shape[4]
    rois = [
        Roi.from_values(
            slices={
                "y": slice(y0 * pixel_size_y, (y0 + h) * pixel_size_y),
                "x": slice(x0 * pixel_size_x, (x0 + w) * pixel_size_x),
            },
            name=name or f"FOV_{i}",
            label=i,
            space="world",
        )
        for i, ((y0, x0), name) in enumerate(zip(layout.offsets, layout.position_names))
    ]
    return RoiTable(rois=rois)
